force-app/main/default/objects/Descuento_Cliente__c/Descuento_Cliente__c.object-meta.xml
<CustomObject>
    <label>Descuento Cliente</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nro Reg</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Descuentos Cliente</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Descuento_Cliente__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Descuentos Cliente</relationshipLabel>
    <relationshipName>Descuentos_Cliente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Detalle_Factura__c/Detalle_Factura__c.object-meta.xml
<CustomObject>
    <label>Detalle Factura</label>
    <nameField>
        <displayFormat>DF-{00000}</displayFormat>
        <label>Detalle Factura Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detalles Facturas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Detalle_Factura__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Detalles Facturas</relationshipLabel>
    <relationshipName>Detalles_Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ICB_ProductServiceImpl.cls
/**********************************************************************************
Desarrollado por: SEIDOR
Autor: Rodrigo Carvallo (RCG)
Proyecto: Maestra de Precios - Perfomance
Descripción: Clase de Product para Maestra de Precios
Test: ICB_ProductService_Test

---------------------------------------------------------------------------------
No. Fecha                Autor                     Descripción
------ ---------- ---------------------------------------------------------------
1.0 11-09-2025            RCG                Creación de la clase.
**********************************************************************************/
public class ICB_ProductServiceImpl{

    /**
    * Retorna una lista de Id de Product2 en base al detalle de compras y los descuento de Maestra de Precios
    * @author Rodrigo Carvallo
    * @param List<Detalle_Factura__c> comprasMaestradePrecios
    * @return Set<Id>
    **/
    public static Set<Id> cargarProductIds(List<Detalle_Factura__c> comprasMaestradePrecios, List<Descuento_Cliente__c> descuentosClienteMaestradePrecios) {
        Set<Id> productIds = new Set<Id>();
        // Cargar los Product2 Ids en productIds desde las compras (Detalle_Factura__c)
        for (Detalle_Factura__c detalle : comprasMaestradePrecios) {
            if (detalle.Product__c != null) {
                productIds.add(detalle.Product__c);
            }
        }
        
        // Cargar los Product2 Ids en productIds desde los descuentos (Descuento_Cliente__c)
        for (Descuento_Cliente__c descuento : descuentosClienteMaestradePrecios) {
            if (descuento.Producto__c != null) {
                productIds.add(descuento.Producto__c);
            }
        }
        return productIds;
    }

}