force-app/main/default/objects/Detalle_Factura__c/Detalle_Factura__c.object-meta.xml
<CustomObject>
    <label>Detalle Factura</label>
    <nameField>
        <displayFormat>DF-{00000}</displayFormat>
        <label>Detalle Factura Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detalles Facturas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Detalle_Factura__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Detalles Facturas</relationshipLabel>
    <relationshipName>Detalles_Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Fecha_maxima_de_descuento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_maxima_de_descuento__c</fullName>
    <label>Fecha máxima de descuento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ICB_UtilsServiceImpl.cls
/**********************************************************************************
Desarrollado por: SEIDOR
Autor: Rodrigo Carvallo (RCG)
Proyecto: Maestra de Precios - Perfomance
Descripción: Clase de utilitarios para Maestra de Precios
Test: ICB_UtilsService_Test

---------------------------------------------------------------------------------
No. Fecha                Autor                     Descripción
------ ---------- ---------------------------------------------------------------
1.0 11-09-2025            RCG                Creación de la clase.
**********************************************************************************/
public class ICB_UtilsServiceImpl{

    /**
    * Método que retorna el nombre en formato texto del mes en curso
    * @author Rodrigo Carvallo
    * @return String
    **/
    public static String generarEncabezado(){
        Date today = System.today();
        List<String> meses = new List<String>{
            'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'
                };
        String mesTexto = meses[today.month() - 1];
        String anio = String.valueOf(today.year());
        return mesTexto.toUpperCase() + ' ' + anio;
    }

    /**
    * Método para formatear fechas de componente
    * @author Rodrigo Carvallo
    * @param List<Detalle_Factura__c> comprasMaestradePrecios
    **/
    public static void formatearFechas(List<Detalle_Factura__c> comprasMaestradePrecios){
        system.debug('formatear fecha ');
        for (Detalle_Factura__c detalle : comprasMaestradePrecios) {
            // Descuento_Cliente__r nunca tuvo valores, usar Product__r.Fecha_maxima_de_descuento__c
            Date fecha = detalle.Product__r.Fecha_maxima_de_descuento__c;
            system.debug('fecha ' + detalle.Product__r.Fecha_maxima_de_descuento__c);
            // Fecha_Vencimiento_Formateada__c no existe en Detalle_Factura__c, campo eliminado
            // La fecha de vencimiento está disponible en detalle.Product__r.Fecha_maxima_de_descuento__c si se necesita
        }
    }

}